### ISSUE TITLE
Exception caught by foundation library

### ISSUE THREAD

**Issue by joyal670** [ElG0hary/scroll_to_hide#1]
on scrolling, getting this error

════════ Exception caught by foundation library ════════════════════════════════
setState() called after dispose(): _ScrollToHideState#fcdd1(lifecycle state: defunct, not mounted)

**Comment by ElG0hary** [comment]
❤️❤️❤️❤️
Thanks For your Reach, I will be working on.

**Comment by joyal670** [comment]
`  void listen() {
    if (mounted) {
      final direction = scrollController.position.userScrollDirection;
      if (direction == ScrollDirection.forward) {
        show();
      } else if (direction == ScrollDirection.reverse) {
        hide();
      }
    }
  }

  @override
  void initState() {
    scrollController.addListener(listen);
    super.initState();
  }

  @override
  void dispose() {
    scrollController.removeListener(listen);
    scrollController.dispose();
    super.dispose();
  }
`

**Comment by joyal670** [comment]
// added this
  
void listen() {
    if (mounted) {
      final direction = scrollController.position.userScrollDirection;
      if (direction == ScrollDirection.forward) {
        show();
      } else if (direction == ScrollDirection.reverse) {
        hide();
      }
    }
  }

  @override
  void initState() {
    scrollController.addListener(listen);
    super.initState();
  }

  @override
  void dispose() {
    scrollController.removeListener(listen);
    scrollController.dispose();
    super.dispose();
  }

**Comment by ElG0hary** [comment]
Updated with the Fix.❤️
